services:

  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bs23
      POSTGRES_DB: ecommerce
    volumes:
    - db-data:/var/lib/postgresql/data
    networks:
    - backend
    
  app:
    build: .
    ports:
      - '3030:3030'
    environment:
      DATABASE_URL: "postgresql://postgres:bs23@postgres:5432/ecommerce"
    depends_on:
      - postgres
    networks:
      - backend

volumes:
  db-data:

networks:
  backend: