name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to your default branch
  pull_request:
    branches:
      - main  # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Adjust this to your project's Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm run test
        
      - name: Set environment variables
        env:
          PORT: ${{ secrets.PORT }}
        run: echo "PORT is set"

      # Optional: Build the application
      - name: Build application
        run: npm run build
        
      # Optional: Need to learn, how to run all db scripts on client db

      # Optional: Deploy step
      # Uncomment and configure according to your deployment method
      # - name: Deploy to Heroku
      #   uses: akhilmhdh/heroku-deploy@v3.2.8
      #   with:
      #     heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
      #     heroku_email: ${{ secrets.HEROKU_EMAIL }}
      #     heroku_api_key: ${{ secrets.HEROKU_API_KEY }}

